In [3]:
!pip install pymysql

Collecting pymysql
  Using cached PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Using cached PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [2]:
import os 
import pymysql
from pymysql.constants import CLIENT

db = pymysql.connect(
	host='localhost',
    port=3306,
    user='root',
    passwd=os.environ['PASSWORD'],
    db='sesacChatbotDB',
    charset='utf8',
    client_flag=CLIENT.MULTI_STATEMENTS
)

In [14]:
cursor = db.cursor()

In [ ]:
sql = """
-- 온라인 강의 테이블
CREATE TABLE online_course_tbl (
    course_id VARCHAR(255) PRIMARY KEY,          -- 강의 고유 ID
    course_title VARCHAR(255)UNIQUE,                   -- 강의 제목
    course_category VARCHAR(255),                -- 강의 분류
    course_difficulty VARCHAR(255),              -- 강의 난도
    support_period VARCHAR(255),                 -- 지원 기간
    class_period VARCHAR(255),                   -- 수업 기간
    class_duration VARCHAR(255),                 -- 수업 시간
    target_audience TEXT,                        -- 수강 대상
    course_objective TEXT,                       -- 교육 목표
    completion_criteria TEXT                     -- 이수 기준
);

-- 오프라인 강의 테이블
CREATE TABLE offline_course_tbl (
    course_id VARCHAR(255) PRIMARY KEY,          -- 강의 고유 ID
    course_title VARCHAR(255)UNIQUE,                   -- 강의 제목
    course_category VARCHAR(255),                -- 강의 분류
    support_period VARCHAR(255),                 -- 지원 기간
    class_period VARCHAR(255),                   -- 수업 기간
    class_duration VARCHAR(255),                 -- 수업 시간
    education_location TEXT,                     -- 교육 장소
    target_audience TEXT,                        -- 수강 대상
    application_method TEXT,                     -- 신청 방법
    selection_criteria TEXT,                     -- 선발 기준
    educational_goals TEXT,                      -- 교육 목표
    completion_criteria TEXT                     -- 이수 기준
);

-- 강의 목차 테이블
CREATE TABLE course_content_tbl (
    content_id varchar(255) PRIMARY KEY,  -- 목차 항목 고유 ID
    course_id VARCHAR(255),                     -- 강의 ID (외래키)
    content_index INT,                          -- 목차 항목 순서 (index)
    content TEXT,                               -- 목차 내용
    FOREIGN KEY (course_id) REFERENCES online_course_tbl(course_id)
        ON DELETE CASCADE,                       -- 강의 삭제 시 해당 목차도 삭제
    FOREIGN KEY (course_id) REFERENCES offline_course_tbl(course_id)
        ON DELETE CASCADE  
);

-- 강의 상세 이미지 텍스트 테이블 예
CREATE TABLE course_img_text_tbl (
    image_id INT AUTO_INCREMENT PRIMARY KEY,
    course_id varchar(255),
    image_text text,
    FOREIGN KEY (course_id) REFERENCES online_course_tbl(course_id)
        ON DELETE CASCADE,  
  FOREIGN KEY (course_id) REFERENCES offline_course_tbl(course_id)
        ON DELETE CASCADE     
);


-- 공지 테이블
CREATE TABLE notice_tbl (
    notice_id varchar(255) PRIMARY KEY,            -- 공지사항 고유번호
    notice_title VARCHAR(255),                -- 공지사항 제목
    notice_date DATE,                          -- 공지사항 날짜
    notice_content TEXT                          -- 공지사항 내용
);

-- 공지 이미지 텍스트 테이블 예
CREATE TABLE notice_img_text_tbl (
    image_id INT AUTO_INCREMENT PRIMARY KEY,  -- 이미지 고유 ID
    notice_id varchar(255),                               -- 공지사항 고유번호 (foreign key)
    image_text TEXT,                          -- Base64로 인코딩된 이미지 텍스트 데이터
    FOREIGN KEY (notice_id) REFERENCES notice_tbl(notice_id)  -- 공지사항 테이블과 외래키 관계
);

-- 리뷰 데이터
CREATE TABLE review_tbl (
    review_id varchar(255) PRIMARY KEY,   -- 리뷰 고유 ID
    course_title VARCHAR(255),           -- 교육 과정명
    rating INT,                        -- 평가 점수 (1 ~ 5)
    review_date DATE,                  -- 리뷰 작성일 (형식: YYYY-MM-DD)
    review_content TEXT,                -- 리뷰 내용,
    FOREIGN KEY (course_title) REFERENCES offline_course_tbl(course_title),
    FOREIGN KEY (course_title) REFERENCES online_course_tbl(course_title)
);

-- 묻고 답하기
CREATE TABLE qna_tbl (
    qna_id varchar(255) PRIMARY KEY,    -- 질문 고유번호
    question_title VARCHAR(255) NOT NULL,            -- 질문 제목
    question_content TEXT NOT NULL,                  -- 질문 내용
    answer_content TEXT                              -- 답변 내용 (답변이 없는 경우 NULL 허용)
);

-- 자주하는질문 이미지 텍스트 테이블 예
CREATE TABLE faq_img_text_tbl (
    image_id INT AUTO_INCREMENT PRIMARY KEY,  -- 이미지 고유 ID
    image_text TEXT                          -- Base64로 인코딩된 이미지 텍스트 데이터
);
"""
 
cursor.execute(sql)
db.commit()